#Infos
loss : "BCE Loss"
architecture: "Ensemble U-net"
sweep: 0

# training
learning_rate: 0.0001
batch_size: 16
epochs: 2
ensemble_size: 2 #number of samples drawn from the weight distribution determined by MC-Dropout

#Turn WandB on and off
W: 1

# data
dataset : "brats"
image_size: 64